version: '3.8'

services:
  db:
    image: postgres:13
    container_name: divida_politica_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: desafio_backend_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - divida_politica_network

  web:
    image: ruby:3.1.2
    container_name: divida_politica_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: your_username
      DATABASE_PASSWORD: your_password
      DATABASE_PORT: 5432
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - divida_politica_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  divida_politica_network:
    driver: bridge